import { db } from "@/lib/db";
import { requireAdmin } from "@/lib/auth";
import { AdminHeading } from "../_components";
import { deleteCategoryAction, saveCategoryAction } from "../actions";

export default async function AdminCategoriesPage() {
  await requireAdmin();
  const categories = await db.category.findMany({ orderBy: { order: "asc" }, include: { _count: { select: { services: true } } } });
  return <><AdminHeading title="Categorías" /><div className="grid gap-6 lg:grid-cols-[1fr_360px]"><div className="space-y-4">{categories.map((category) => <form key={category.id} action={saveCategoryAction} className="grid gap-3 rounded-2xl border bg-white p-5 shadow-sm md:grid-cols-[1fr_1fr_80px_110px_auto] md:items-end"><input type="hidden" name="id" value={category.id} /><label className="text-xs">Nombre<input name="name" required defaultValue={category.name} className="mt-1 h-9 w-full rounded-lg border px-3 text-sm" /></label><label className="text-xs">Slug<input name="slug" required defaultValue={category.slug} className="mt-1 h-9 w-full rounded-lg border px-3 text-sm" /></label><label className="text-xs">Orden<input name="order" type="number" defaultValue={category.order} className="mt-1 h-9 w-full rounded-lg border px-3 text-sm" /></label><label className="text-xs">Estado<select name="active" defaultValue={String(category.active)} className="mt-1 h-9 w-full rounded-lg border px-2 text-sm"><option value="true">Activa</option><option value="false">Inactiva</option></select></label><div className="flex items-center gap-3"><button className="text-sm font-semibold text-navy">Guardar</button><button formAction={deleteCategoryAction} className="text-sm text-red-600">{category._count.services ? "Desactivar" : "Eliminar"}</button></div><label className="text-xs md:col-span-5">Descripción<textarea name="description" defaultValue={category.description ?? ""} className="mt-1 min-h-16 w-full rounded-lg border p-2 text-sm" /></label><label className="text-xs md:col-span-5">Imagen URL<input name="image" type="url" defaultValue={category.image ?? ""} className="mt-1 h-9 w-full rounded-lg border px-3 text-sm" /></label></form>)}</div><form action={saveCategoryAction} className="space-y-4 rounded-2xl border bg-white p-5 shadow-sm"><h2 className="font-heading text-xl text-navy">Nueva categoría</h2><input name="name" required placeholder="Nombre" className="h-9 w-full rounded-lg border px-3 text-sm" /><input name="slug" required placeholder="slug" className="h-9 w-full rounded-lg border px-3 text-sm" /><textarea name="description" placeholder="Descripción" className="w-full rounded-lg border p-3 text-sm" /><input name="image" type="url" placeholder="Imagen URL" className="h-9 w-full rounded-lg border px-3 text-sm" /><input name="order" type="number" defaultValue="99" className="h-9 w-full rounded-lg border px-3 text-sm" /><input type="hidden" name="active" value="true" /><button className="rounded-full bg-navy px-5 py-2 text-sm font-semibold text-white">Crear categoría</button></form></div></>;
}
