import { db } from "@/lib/db";
import { requireAdmin } from "@/lib/auth";
import { AdminHeading } from "../_components";
import { saveLocationAction } from "../actions";

export default async function LocationsPage() {
  await requireAdmin();
  const locations = await db.location.findMany({ orderBy: { order: "asc" } });
  return <><AdminHeading title="Sedes" /><div className="grid gap-6 lg:grid-cols-2">{locations.map((location) => <form key={location.id} action={saveLocationAction} className="grid gap-3 rounded-2xl border bg-white p-5 shadow-sm sm:grid-cols-2"><input type="hidden" name="id" value={location.id} /><label className="text-xs">Nombre<input name="name" required defaultValue={location.name} className="mt-1 h-9 w-full rounded-lg border px-3 text-sm" /></label><label className="text-xs">Ciudad<input name="city" required defaultValue={location.city} className="mt-1 h-9 w-full rounded-lg border px-3 text-sm" /></label><label className="text-xs sm:col-span-2">Dirección<input name="address" required defaultValue={location.address} className="mt-1 h-9 w-full rounded-lg border px-3 text-sm" /></label><label className="text-xs">Teléfono<input name="phone" defaultValue={location.phone ?? ""} className="mt-1 h-9 w-full rounded-lg border px-3 text-sm" /></label><label className="text-xs">Maps URL<input name="mapsUrl" type="url" defaultValue={location.mapsUrl ?? ""} className="mt-1 h-9 w-full rounded-lg border px-3 text-sm" /></label><label className="text-xs">Orden<input name="order" type="number" defaultValue={location.order} className="mt-1 h-9 w-full rounded-lg border px-3 text-sm" /></label><label className="text-xs">Estado<select name="active" defaultValue={String(location.active)} className="mt-1 h-9 w-full rounded-lg border px-2 text-sm"><option value="true">Activa</option><option value="false">Inactiva</option></select></label><button className="rounded-full bg-navy px-4 py-2 text-sm font-semibold text-white sm:col-span-2">Guardar sede</button></form>)}<form action={saveLocationAction} className="grid gap-3 rounded-2xl border border-dashed bg-white p-5 shadow-sm sm:grid-cols-2"><h2 className="font-heading text-xl text-navy sm:col-span-2">Nueva sede</h2><label className="text-xs">Nombre<input name="name" required className="mt-1 h-9 w-full rounded-lg border px-3 text-sm" /></label><label className="text-xs">Ciudad<input name="city" required className="mt-1 h-9 w-full rounded-lg border px-3 text-sm" /></label><label className="text-xs sm:col-span-2">Dirección<input name="address" required className="mt-1 h-9 w-full rounded-lg border px-3 text-sm" /></label><label className="text-xs">Teléfono<input name="phone" className="mt-1 h-9 w-full rounded-lg border px-3 text-sm" /></label><label className="text-xs">Maps URL<input name="mapsUrl" type="url" className="mt-1 h-9 w-full rounded-lg border px-3 text-sm" /></label><label className="text-xs">Orden<input name="order" type="number" defaultValue="99" className="mt-1 h-9 w-full rounded-lg border px-3 text-sm" /></label><input type="hidden" name="active" value="true" /><button className="rounded-full bg-navy px-4 py-2 text-sm font-semibold text-white sm:col-span-2">Crear sede</button></form></div></>;
}
