import { db } from "@/lib/db";
import { requireAdmin } from "@/lib/auth";
import { AdminHeading } from "../_components";
import { MarkPaid, StatusForm } from "../status-form";

export default async function OrdersPage() {
  await requireAdmin();
  const orders = await db.order.findMany({ orderBy: { createdAt: "desc" }, take: 100, include: { patient: true, service: true, location: true, payments: true } });
  return <><AdminHeading title="Pedidos y pagos" /><div className="rounded-2xl border bg-white p-5 shadow-sm"><table className="w-full text-sm"><thead><tr className="border-b text-left text-muted-foreground"><th className="p-3">Orden</th><th className="p-3">Paciente</th><th className="p-3">Servicio</th><th className="p-3">Sede / fecha</th><th className="p-3">Objetivo</th><th className="p-3">Total</th><th className="p-3">Puntos</th><th className="p-3">Referido</th><th className="p-3">Método</th><th className="p-3">Estado</th><th className="p-3" /></tr></thead><tbody>{orders.map((order) => <tr key={order.id} className="border-b"><td className="p-3 text-xs">{order.id.slice(-8)}</td><td className="p-3">{order.patient.firstName} {order.patient.lastName}</td><td className="p-3">{order.service.name}</td><td className="p-3">{order.location?.name ?? "—"}{order.preferredDate && <span className="block text-xs text-muted-foreground">{order.preferredDate.toLocaleDateString("es-EC")} · {order.preferredSlot ?? "—"}</span>}</td><td className="max-w-48 p-3 text-xs">{order.patientGoal ?? "—"}</td><td className="p-3">${Number(order.total).toFixed(2)}</td><td className="p-3">{order.pointsRedeemed}</td><td className="p-3">{order.referralCode ?? "—"}</td><td className="p-3">{order.paymentMethod}</td><td className="p-3"><StatusForm model="order" id={order.id} value={order.status} options={["PENDING", "PAID", "FAILED", "CANCELLED", "REFUNDED"]} /></td><td className="p-3">{order.status !== "PAID" && (order.paymentMethod === "TRANSFER" || order.paymentMethod === "CASH") && <MarkPaid id={order.id} />}</td></tr>)}</tbody></table></div></>;
}
