import { db } from "@/lib/db";
import { getPointsSummary } from "@/lib/rewards";
import { requireAdmin } from "@/lib/auth";
import { AdminHeading } from "../_components";
import { adjustPointsAction, toggleRewardAction } from "../actions";

export default async function RewardsAdminPage() {
  await requireAdmin();
  const [accounts, rewards] = await Promise.all([
    db.patientAccount.findMany({ include: { patient: true }, orderBy: { createdAt: "desc" } }),
    db.reward.findMany({ orderBy: { order: "asc" } }),
  ]);
  const accountRows = await Promise.all(accounts.map(async (account) => ({ account, summary: await getPointsSummary(account.patientId), referrals: await db.patientAccount.count({ where: { referredById: account.id } }) })));
  return <><AdminHeading title="Recompensas" /><div className="grid gap-8 lg:grid-cols-[1.2fr_0.8fr]"><section className="rounded-2xl border bg-white p-5 shadow-sm"><h2 className="font-heading text-2xl text-navy">Cuentas de pacientes</h2><div className="mt-5 overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr className="border-b text-muted-foreground"><th className="p-3">Paciente</th><th className="p-3">Correo</th><th className="p-3">Saldo</th><th className="p-3">Nivel</th><th className="p-3">Referidos</th></tr></thead><tbody>{accountRows.map(({ account, summary, referrals }) => <tr key={account.id} className="border-b"><td className="p-3">{account.patient.firstName} {account.patient.lastName}</td><td className="p-3">{account.email}</td><td className="p-3">{summary.balance}</td><td className="p-3">{summary.tier}</td><td className="p-3">{referrals}</td></tr>)}</tbody></table></div></section><section className="rounded-2xl border bg-white p-5 shadow-sm"><h2 className="font-heading text-2xl text-navy">Ajustar puntos</h2><form action={adjustPointsAction} className="mt-5 space-y-3"><select name="patientId" required className="h-10 w-full rounded-lg border px-3 text-sm"><option value="">Paciente</option>{accounts.map((account) => <option key={account.patientId} value={account.patientId}>{account.patient.firstName} {account.patient.lastName} · {account.email}</option>)}</select><input name="points" type="number" required placeholder="Puntos (use negativo para descontar)" className="h-10 w-full rounded-lg border px-3 text-sm" /><select name="reason" required className="h-10 w-full rounded-lg border px-3 text-sm"><option value="ADJUSTMENT">Ajuste</option><option value="PROTOCOL_COMPLETED">Protocolo completado</option><option value="PUNCTUAL_ATTENDANCE">Asistencia puntual</option><option value="FOLLOW_UP">Seguimiento</option><option value="ANNIVERSARY">Aniversario</option></select><textarea name="description" required placeholder="Descripción" className="min-h-20 w-full rounded-lg border p-3 text-sm" /><button className="rounded-full bg-navy px-5 py-2 text-sm font-semibold text-white">Guardar ajuste</button></form></section></div><section className="mt-8 rounded-2xl border bg-white p-5 shadow-sm"><h2 className="font-heading text-2xl text-navy">Rewards disponibles</h2><div className="mt-5 grid gap-3 md:grid-cols-2">{rewards.map((reward) => <div key={reward.id} className="flex items-center justify-between gap-4 rounded-xl border p-4"><div><p className="font-semibold text-navy">{reward.name}</p><p className="mt-1 text-sm text-muted-foreground">{reward.pointsCost} puntos · Nivel {reward.minTier}</p></div><form action={toggleRewardAction}><input type="hidden" name="id" value={reward.id} /><button className="text-sm font-semibold text-gold">{reward.active ? "Desactivar" : "Activar"}</button></form></div>)}</div></section></>;
}
