import Link from "next/link";
import Image from "next/image";
import { Button } from "@/components/ui/button";
import { SectionHeading } from "@/components/site/section-heading";
import { MedicalDisclaimer } from "@/components/site/disclaimers";
import { db } from "@/lib/db";
import { categoryImage, SITE_IMAGES } from "@/lib/images";

export const metadata = { title: "Dr. Edwin Ayala | SILHO Medicina Estética", description: "Conoce al profesional de SILHO Medicina Estética." };

export default async function ProfessionalPage() {
  const professional = await db.professional.findFirst({ where: { active: true } });
  if (!professional) return <main className="mx-auto max-w-3xl px-6 py-24"><SectionHeading title="Información del profesional" description="La información estará disponible próximamente." /></main>;
  return <main><section className="bg-navy px-6 py-20 text-white lg:px-10 lg:py-28"><div className="mx-auto grid max-w-7xl gap-12 lg:grid-cols-[0.8fr_1.2fr] lg:items-center"><div className="relative aspect-[4/5] overflow-hidden rounded-[2rem]"><Image src={SITE_IMAGES.doctor} alt="Atención médica en SILHO" fill priority sizes="(max-width: 1024px) 100vw, 40vw" className="object-cover" /></div><div><p className="text-xs uppercase tracking-[0.24em] text-gold-light">Profesional SILHO</p><h1 className="mt-5 font-heading text-5xl md:text-6xl">{professional.name}</h1><p className="mt-3 text-gold-light">{professional.title}</p><p className="mt-7 max-w-xl text-lg leading-8 text-white/70">{professional.bio}</p><Button asChild className="mt-8 rounded-full bg-gold text-ink hover:bg-gold-light"><Link href="/reservar">Reservar valoración</Link></Button></div></div></section><section className="mx-auto max-w-7xl px-6 py-12 lg:px-10"><div className="grid gap-4 md:grid-cols-3"><div className="relative aspect-[4/3] overflow-hidden rounded-2xl"><Image src={SITE_IMAGES.clinic} alt="Espacio clínico SILHO" fill sizes="(max-width: 768px) 100vw, 33vw" className="object-cover" /></div><div className="relative aspect-[4/3] overflow-hidden rounded-2xl"><Image src={SITE_IMAGES.consultation} alt="Consulta médica en SILHO" fill sizes="(max-width: 768px) 100vw, 33vw" className="object-cover" /></div><div className="relative aspect-[4/3] overflow-hidden rounded-2xl"><Image src={categoryImage("valoracion")} alt="Valoración médica en SILHO" fill sizes="(max-width: 768px) 100vw, 33vw" className="object-cover" /></div></div></section><section className="mx-auto max-w-5xl px-6 py-12 lg:px-10 lg:py-20"><SectionHeading eyebrow="Enfoque clínico" title="Una valoración facial con prioridades claras" description="Evaluamos el rostro completo, explicamos las alternativas y documentamos los límites del plan." /><div className="mt-12 grid gap-8 md:grid-cols-2"><div><h2 className="font-heading text-2xl text-navy">Cómo es la valoración</h2><p className="mt-3 text-sm leading-7 text-muted-foreground">Revisamos objetivos, antecedentes, piel, proporciones, tratamientos previos y cuidados. Con esa información diseñamos un protocolo por sesiones cuando corresponde.</p></div><div><h2 className="font-heading text-2xl text-navy">Compromisos SILHO</h2><ul className="mt-3 space-y-3 text-sm leading-6 text-muted-foreground"><li>• Productos y tecnologías con registro sanitario.</li><li>• Protocolos de bioseguridad.</li><li>• Seguimiento posterior.</li><li>• Consentimiento informado antes de cada procedimiento.</li></ul></div></div><MedicalDisclaimer className="mt-12" /></section></main>;
}
