import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { ArrowRight, MapPin, ShieldCheck } from "lucide-react";
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";
import { Button } from "@/components/ui/button";
import { LeadForm } from "@/components/site/lead-form";
import { MedicalDisclaimer } from "@/components/site/disclaimers";
import { SectionHeading } from "@/components/site/section-heading";
import { TrackedLink } from "@/components/site/tracked-link";
import { SITE_IMAGES } from "@/lib/images";
import { getSettings } from "@/lib/settings";
import { getWebDiscountFor } from "@/lib/pricing";
import { routeList } from "@/lib/routes";
import { TIERS } from "@/lib/rewards";
import { db } from "@/lib/db";

export const metadata: Metadata = {
  title: "SILHO | Medicina Estética Facial · Dr. Edwin Ayala",
  description: "Clínica de medicina estética facial en Ecuador y Salinas. Valoración, acné, cicatrices y rejuvenecimiento facial con el Dr. Edwin Ayala.",
};

const faqs = [
  ["¿Cómo comienza un tratamiento facial?", "Comienza con una valoración médica. Revisamos sus objetivos, antecedentes y el estado de su rostro antes de diseñar un plan."],
  ["¿Qué ruta es adecuada para mí?", "Puede explorar las tres rutas faciales o usar nuestro orientador digital. La indicación final se define en valoración."],
  ["¿Qué incluye la valoración?", "Evaluamos el rostro completo, revisamos antecedentes y explicamos prioridades, alternativas, cuidados y seguimiento."],
  ["¿El beneficio web aplica a todos los tratamientos?", "Aplica al servicio de valoración y a procedimientos elegibles según las condiciones publicadas. No aplica a cirugías ni servicios sujetos a cotización manual."],
  ["¿Puedo usar puntos de SILHO Face Rewards?", "Los puntos se acumulan en acciones elegibles y pueden canjearse en múltiplos de 100, dentro de los límites del programa."],
  ["¿Los resultados están garantizados?", "No. Los resultados varían entre pacientes y dependen de la valoración, la indicación y la evolución individual."],
];

export default async function Home() {
  const [professional, locations, cases, valuation, settings] = await Promise.all([
    db.professional.findFirst({ where: { active: true }, orderBy: { name: "asc" } }),
    db.location.findMany({ where: { active: true }, orderBy: { order: "asc" } }),
    db.beforeAfter.findMany({ where: { published: true, patientConsent: true }, orderBy: { createdAt: "desc" }, take: 3 }),
    db.service.findUnique({ where: { slug: "valoracion-valoracion-estetica-facial" }, select: { slug: true, name: true, basePrice: true, discountEligible: true } }),
    getSettings(["WHATSAPP_NUMBER", "CLINIC_EMAIL", "CLINIC_HOURS", "WEB_TREATMENT_BONUS_USD", "WEB_BONUS_DAYS", "WEB_WEEKLY_SLOTS", "WEB_OFFER_VALID_UNTIL", "ASSESSMENT_SERVICE_SLUG"]),
  ]);
  const webDiscount = valuation ? await getWebDiscountFor(valuation) : 25;
  const faqJson = { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: faqs.map(([name, text]) => ({ "@type": "Question", name, acceptedAnswer: { "@type": "Answer", text } })) };
  const clinicJson = {
    "@context": "https://schema.org",
    "@type": "MedicalClinic",
    name: "SILHO Medicina Estética Facial",
    url: process.env.NEXT_PUBLIC_APP_URL ?? "http://localhost:3000",
    telephone: settings.WHATSAPP_NUMBER ? `+${settings.WHATSAPP_NUMBER}` : undefined,
    address: locations.map((location) => ({ "@type": "PostalAddress", addressLocality: location.city, streetAddress: location.address, addressCountry: "EC" })),
    physician: professional ? { "@type": "Physician", name: professional.name } : undefined,
  };
  return (
    <main>
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqJson).replace(/</g, "\\u003c") }} />
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(clinicJson).replace(/</g, "\\u003c") }} />
      <section className="relative overflow-hidden bg-navy px-6 py-24 text-white lg:px-10 lg:py-32">
        <Image src={SITE_IMAGES.hero} alt="Espacio de atención estética SILHO" fill priority sizes="(max-width: 1024px) 100vw, 50vw" className="object-cover opacity-30 lg:opacity-40" />
        <div className="absolute inset-0 bg-gradient-to-r from-navy via-navy/90 to-navy/40" />
        <div className="relative mx-auto max-w-7xl">
          <p className="text-xs font-semibold uppercase tracking-[0.25em] text-gold-light">SILHO · Medicina estética facial</p>
          <h1 className="mt-6 max-w-4xl font-heading text-5xl leading-[1.05] tracking-tight md:text-7xl">Especialistas en salud, armonización y rejuvenecimiento del rostro.</h1>
          <p className="mt-7 max-w-2xl text-lg leading-8 text-white/75">Rejuvenecer no significa cambiar su rostro. Diseñamos tratamientos faciales que respetan su identidad, con valoración médica del Dr. Edwin Ayala.</p>
          <div className="mt-9 flex flex-col gap-3 sm:flex-row">
            <Button asChild className="rounded-full bg-gold px-7 text-ink hover:bg-gold-light"><TrackedLink href="/reservar" event="cta_reservar_click" params={{ location: "home_hero" }}>Agenda tu valoración facial <ArrowRight /></TrackedLink></Button>
            <Button asChild variant="outline" className="rounded-full border-white/30 bg-transparent px-7 text-white hover:bg-white/10"><Link href="/descubre-tu-ruta">Descubre tu ruta facial</Link></Button>
          </div>
          {valuation && <div className="mt-10 max-w-xl rounded-2xl border border-gold/40 bg-white/10 p-5 backdrop-blur"><p className="text-sm font-semibold text-gold-light">Reserve en línea y acceda a beneficios exclusivos</p><div className="mt-2 flex flex-wrap items-baseline gap-3"><span className="text-sm text-white/55 line-through">USD {Number(valuation.basePrice).toFixed(2)}</span><span className="font-heading text-2xl">USD {(Number(valuation.basePrice) * (1 - webDiscount / 100)).toFixed(2)}</span><span className="text-sm text-white/65">{webDiscount}% beneficio web</span></div></div>}
        </div>
      </section>
      <section className="mx-auto max-w-7xl px-6 py-20 lg:px-10">
        <SectionHeading eyebrow="Encuentre su ruta" title="Tres caminos para cuidar su rostro" description="Cada ruta parte de una valoración médica y de un plan diseñado alrededor de sus objetivos." />
        <div className="mt-10 grid gap-5 lg:grid-cols-3">{routeList.map((route) => <Link key={route.slug} href={`/${route.slug}`} className="group overflow-hidden rounded-3xl border bg-white shadow-sm transition hover:-translate-y-0.5 hover:shadow-md"><div className="relative aspect-[4/3] overflow-hidden"><Image src={route.image} alt={route.name} fill sizes="(max-width: 1024px) 100vw, 33vw" className="object-cover transition duration-500 group-hover:scale-105" /><div className="absolute inset-0 bg-gradient-to-t from-navy/85 via-transparent to-transparent" /><div className="absolute inset-x-0 bottom-0 p-5 text-white"><p className="text-xs uppercase tracking-[0.18em] text-gold-light">{route.navLabel}</p><h2 className="mt-2 font-heading text-2xl">{route.name}</h2></div></div><div className="p-5"><p className="text-sm leading-6 text-muted-foreground">{route.tagline}</p><p className="mt-4 text-sm font-semibold text-navy">Desde USD {route.priceFrom} <ArrowRight className="ml-1 inline size-4" /></p></div></Link>)}</div>
        <div className="mt-8 rounded-3xl bg-[#f5f1e8] p-6 md:flex md:items-center md:justify-between md:gap-8"><div><p className="text-xs uppercase tracking-[0.2em] text-gold">¿No sabe por dónde empezar?</p><p className="mt-2 font-heading text-2xl text-navy">Descubra su ruta facial en cinco pasos.</p></div><Button asChild className="mt-5 rounded-full bg-navy text-white hover:bg-navy/90 md:mt-0"><Link href="/descubre-tu-ruta">Usar el orientador <ArrowRight /></Link></Button></div>
      </section>
      <section className="bg-[#fafaf9] px-6 py-20 lg:px-10"><div className="mx-auto max-w-7xl"><SectionHeading eyebrow="La diferencia SILHO" title="Un plan antes que un producto" /><div className="mt-10 grid gap-5 md:grid-cols-2 lg:grid-cols-4">{[["Sólo rostro", "Una clínica enfocada exclusivamente en salud, armonización y rejuvenecimiento facial."], ["Plan antes que producto", "Evaluamos el rostro completo y priorizamos lo que realmente necesita atención."], ["Un mismo médico", "El Dr. Edwin Ayala valora y acompaña el plan facial."], ["Seguimiento posterior", "Controlamos la evolución y definimos los siguientes pasos con claridad."]].map(([title, text], index) => <div key={title} className="rounded-2xl border bg-white p-6"><div className="flex size-10 items-center justify-center rounded-full bg-[#f5f1e8] text-sm font-semibold text-gold">0{index + 1}</div><h3 className="mt-5 font-heading text-xl text-navy">{title}</h3><p className="mt-3 text-sm leading-6 text-muted-foreground">{text}</p></div>)}</div></div></section>
      {professional && <section className="bg-navy px-6 py-20 text-white lg:px-10"><div className="mx-auto grid max-w-7xl gap-12 lg:grid-cols-[0.8fr_1.2fr] lg:items-center"><div className="relative aspect-[2/3] overflow-hidden rounded-3xl bg-white/5"><Image src={SITE_IMAGES.doctor} alt={professional.name} fill sizes="(max-width: 1024px) 100vw, 35vw" className="object-cover" /></div><div><p className="text-xs uppercase tracking-[0.24em] text-gold-light">El profesional</p><h2 className="mt-4 font-heading text-4xl">{professional.name}</h2><p className="mt-2 text-gold-light">{professional.title}</p><p className="mt-6 max-w-xl text-lg leading-8 text-white/70">{professional.bio.split(/\n+/)[0]}</p><Button asChild variant="outline" className="mt-8 rounded-full border-white/30 bg-transparent text-white hover:bg-white/10"><Link href="/dr-edwin-ayala">Conozca el enfoque <ArrowRight /></Link></Button></div></div></section>}
      <section className="mx-auto max-w-7xl px-6 py-20 lg:px-10"><SectionHeading eyebrow="Proceso SILHO" title="Atención clara, de principio a fin" /><div className="mt-10 grid gap-5 md:grid-cols-2 lg:grid-cols-4">{[["01", "Valoración facial", "Evaluamos el rostro completo, sus objetivos y sus antecedentes."], ["02", "Plan personalizado", "Priorizamos lo que necesita atención y diseñamos un protocolo claro."], ["03", "Tratamiento por sesiones", "Aplicamos las técnicas indicadas con cuidados definidos."], ["04", "Control y seguimiento", "Revisamos la evolución y ajustamos el plan cuando corresponde."]].map(([number, title, text]) => <div key={number} className="border-l-2 border-gold pl-5"><p className="text-xs tracking-[0.2em] text-gold">{number}</p><h3 className="mt-3 font-heading text-xl text-navy">{title}</h3><p className="mt-3 text-sm leading-6 text-muted-foreground">{text}</p></div>)}</div></section>
      <section className="bg-[#fafaf9] px-6 py-20 lg:px-10"><div className="mx-auto max-w-7xl"><div className="flex flex-wrap items-end justify-between gap-5"><SectionHeading eyebrow="Casos clínicos autorizados" title="Seguimiento documentado" description="Resultados varían entre pacientes." /><Link href="/casos-clinicos" className="text-sm font-semibold text-navy">Ver casos clínicos <ArrowRight className="ml-1 inline size-4" /></Link></div>{cases.length > 0 ? <div className="mt-10 grid gap-5 md:grid-cols-3">{cases.map((item) => <div key={item.id} className="overflow-hidden rounded-2xl border bg-white"><div className="grid grid-cols-2"><div className="relative aspect-square"><Image src={item.beforeImage} alt={`Antes: ${item.title}`} fill sizes="25vw" className="object-cover" /></div><div className="relative aspect-square"><Image src={item.afterImage} alt={`Después: ${item.title}`} fill sizes="25vw" className="object-cover" /></div></div><p className="p-5 text-sm font-semibold text-navy">{item.title}</p></div>)}</div> : <div className="mt-10 rounded-3xl border bg-white p-8 text-center"><p className="font-heading text-2xl text-navy">Estamos documentando casos con autorización expresa de nuestros pacientes.</p><Link href="/casos-clinicos" className="mt-4 inline-block text-sm font-semibold text-navy">Conozca cómo publicamos casos →</Link></div>}<p className="mt-5 text-xs text-muted-foreground">Resultados varían entre pacientes.</p></div></section>
      <section className="mx-auto max-w-7xl px-6 py-20 lg:px-10"><div className="rounded-[2rem] bg-navy p-8 text-white md:p-12"><p className="text-xs uppercase tracking-[0.24em] text-gold-light">Beneficios web</p><h2 className="mt-4 font-heading text-4xl text-white">Reserve en línea y acceda a beneficios exclusivos.</h2><p className="mt-4 max-w-2xl text-white/70">Condiciones claras para comenzar su valoración facial.</p><div className="mt-10 grid gap-5 md:grid-cols-2 lg:grid-cols-4">{[["Beneficio web", `${webDiscount}% de descuento en la valoración facial.`], ["Bono de tratamiento", `USD ${settings.WEB_TREATMENT_BONUS_USD ?? "50"} aplicables al tratamiento si agenda dentro de ${settings.WEB_BONUS_DAYS ?? "30"} días.`], ["Cupos semanales", `${settings.WEB_WEEKLY_SLOTS ?? "10"} espacios destinados a reservas web.`], ["Vigencia", `Oferta válida hasta ${settings.WEB_OFFER_VALID_UNTIL ?? "2026-12-31"}.`]].map(([title, text]) => <div key={title} className="rounded-2xl border border-white/15 bg-white/5 p-5"><p className="font-semibold text-gold-light">{title}</p><p className="mt-3 text-sm leading-6 text-white/70">{text}</p></div>)}</div><p className="mt-7 text-xs leading-5 text-white/50">Aplican únicamente a servicios elegibles. El bono no es efectivo, no se acumula con otras promociones y queda sujeto a valoración, disponibilidad y condiciones vigentes.</p><Button asChild className="mt-7 rounded-full bg-gold text-ink hover:bg-gold-light"><TrackedLink href="/reservar" event="cta_reservar_click" params={{ location: "home_benefits" }}>Reservar valoración <ArrowRight /></TrackedLink></Button></div></section>
      <section className="bg-[#fafaf9] px-6 py-20 lg:px-10"><div className="mx-auto max-w-7xl"><div className="grid gap-10 lg:grid-cols-[0.85fr_1.15fr] lg:items-center"><div><SectionHeading eyebrow="SILHO Face Rewards" title="Cada paso de su cuidado puede sumar." description="Acumule puntos en acciones elegibles y canjéelos por beneficios autorizados por el equipo médico." /><div className="mt-7 flex flex-wrap gap-3"><Button asChild className="rounded-full bg-navy text-white hover:bg-navy/90"><Link href="/beneficios">Ver beneficios</Link></Button><Link href="/cuenta/registro" className="inline-flex items-center text-sm font-semibold text-navy">Crear cuenta <ArrowRight className="ml-1 size-4" /></Link></div></div><div className="grid gap-4 sm:grid-cols-3">{TIERS.map((tier) => <div key={tier.tier} className="rounded-2xl border bg-white p-5"><p className="text-xs uppercase tracking-[0.18em] text-gold">{tier.tier}</p><p className="mt-3 font-heading text-2xl text-navy">{tier.min}+</p><p className="mt-1 text-xs text-muted-foreground">puntos acumulados</p></div>)}</div></div></div></section>
      <section className="mx-auto max-w-3xl px-6 py-20 lg:px-10"><SectionHeading eyebrow="Preguntas frecuentes" title="Antes de reservar" align="center" /><Accordion className="mt-8">{faqs.map(([question, answer], index) => <AccordionItem key={question} value={`faq-${index}`}><AccordionTrigger className="text-left text-navy">{question}</AccordionTrigger><AccordionContent className="text-muted-foreground">{answer}</AccordionContent></AccordionItem>)}</Accordion><MedicalDisclaimer className="mt-8 rounded-2xl bg-[#f5f1e8] p-5" /></section>
      <section className="bg-[#fafaf9] px-6 py-20 lg:px-10"><div className="mx-auto grid max-w-7xl gap-10 lg:grid-cols-[1fr_0.85fr]"><div><SectionHeading eyebrow="Visítenos" title="Sedes, horarios y contacto" description={settings.CLINIC_HOURS ?? "Lunes a sábado, 09:00–18:00"} /><div className="mt-8 grid gap-4 sm:grid-cols-3">{locations.map((location) => <div key={location.id} className="rounded-2xl border bg-white p-5"><MapPin className="size-5 text-gold" /><h3 className="mt-3 font-heading text-lg text-navy">{location.city}</h3><p className="mt-2 text-sm text-muted-foreground">{location.address}</p>{location.mapsUrl && <a href={location.mapsUrl} target="_blank" rel="noreferrer" className="mt-3 inline-block text-xs font-semibold text-navy">Ver mapa →</a>}</div>)}</div></div><div className="rounded-3xl bg-white p-7 shadow-sm"><h3 className="font-heading text-2xl text-navy">Escriba a SILHO</h3><p className="mt-2 text-sm text-muted-foreground">Nuestro equipo recibe su solicitud y le orienta sobre el siguiente paso.</p><div className="mt-6"><LeadForm buttonLabel="Enviar solicitud" /></div></div></div></section>
      <section className="bg-navy px-6 py-20 text-center text-white lg:px-10"><ShieldCheck className="mx-auto size-8 text-gold" /><h2 className="mt-5 font-heading text-4xl">Su rostro merece un plan correcto.</h2><Button asChild className="mt-8 rounded-full bg-gold text-ink hover:bg-gold-light"><TrackedLink href="/reservar" event="cta_reservar_click" params={{ location: "home_footer" }}>Reservar valoración facial <ArrowRight /></TrackedLink></Button></section>
    </main>
  );
}
