"use client";

import { useActionState, useState } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Switch } from "@/components/ui/switch";
import { saveServiceAction } from "./actions";

type Service = { id?: string; name: string; slug: string; categoryId: string; description: string; shortDescription: string; basePrice: unknown; webPrice?: unknown; priceFrom: boolean; showPrice: boolean; discountEligible: boolean; requiresMedicalAssessment: boolean; requiresManualQuote: boolean; isSurgical: boolean; active: boolean; featured: boolean; durationMinutes?: number | null; image?: string | null };
const flags = [["priceFrom", "Precio desde"], ["showPrice", "Mostrar precio"], ["discountEligible", "Elegible para pronto pago"], ["requiresMedicalAssessment", "Requiere valoración médica"], ["requiresManualQuote", "Requiere cotización manual"], ["isSurgical", "Es quirúrgico"], ["active", "Activo"], ["featured", "Destacado"]] as const;

export function ServiceForm({ service, categories, concerns, selectedConcerns = [] }: { service?: Service; categories: { id: string; name: string }[]; concerns: { slug: string; name: string }[]; selectedConcerns?: string[] }) {
  const [state, action, pending] = useActionState(saveServiceAction, null);
  const [name, setName] = useState(service?.name ?? "");
  const [slug, setSlug] = useState(service?.slug ?? "");
  function makeSlug(value: string) { return value.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g, "").replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, ""); }
  return <form action={action} className="space-y-6 rounded-2xl border bg-white p-6 shadow-sm"><input type="hidden" name="id" value={service?.id ?? ""} /><div className="grid gap-4 md:grid-cols-2"><div><label className="text-sm font-medium">Nombre</label><Input name="name" value={name} onChange={(event) => { setName(event.target.value); if (!service) setSlug(makeSlug(event.target.value)); }} required /></div><div><label className="text-sm font-medium">Slug</label><Input name="slug" value={slug} onChange={(event) => setSlug(event.target.value)} required /></div></div><div className="grid gap-4 md:grid-cols-3"><div><label className="text-sm font-medium">Categoría</label><select name="categoryId" defaultValue={service?.categoryId} className="mt-2 h-9 w-full rounded-lg border bg-white px-3 text-sm">{categories.map((category) => <option key={category.id} value={category.id}>{category.name}</option>)}</select></div><div><label className="text-sm font-medium">Precio regular</label><Input name="basePrice" type="number" step="0.01" defaultValue={String(service?.basePrice ?? "")} required /></div><div><label className="text-sm font-medium">Precio web</label><Input name="webPrice" type="number" step="0.01" defaultValue={String(service?.webPrice ?? "")} /></div></div><Input name="shortDescription" placeholder="Descripción corta" defaultValue={service?.shortDescription} required /><Textarea name="description" placeholder="Descripción completa" defaultValue={service?.description} required rows={5} /><div><p className="mb-3 text-sm font-medium">Preocupaciones relacionadas</p><div className="grid gap-2 sm:grid-cols-3">{concerns.map((concern) => <label key={concern.slug} className="flex items-center gap-2 text-sm"><input type="checkbox" name="concerns" value={concern.slug} defaultChecked={selectedConcerns.includes(concern.slug)} />{concern.name}</label>)}</div></div><div className="grid gap-3 sm:grid-cols-2">{flags.map(([key, label]) => <label key={key} className="flex items-center justify-between rounded-xl border px-4 py-3 text-sm">{label}<Switch name={key} value="true" defaultChecked={service?.[key] ?? (key === "priceFrom" || key === "showPrice" || key === "discountEligible" || key === "active")} /></label>)}</div><div><label className="text-sm font-medium">Duración (minutos)</label><Input name="durationMinutes" type="number" defaultValue={service?.durationMinutes ?? ""} /></div><div><label className="text-sm font-medium">Imagen URL</label><Input name="image" type="text" defaultValue={service?.image ?? ""} /></div>{state?.error && <p role="alert" className="text-sm font-medium text-red-600">{state.error}</p>}<Button type="submit" disabled={pending} className="rounded-full bg-navy text-white hover:bg-navy/90">{pending ? "Guardando…" : "Guardar servicio"}</Button></form>;
}
